# Task:

    

### Create Numpy Matrix and try to slice it and try to index multiple variable

In [6]:
import numpy as np

In [4]:
#Creating Matrix
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
print(arr[1:5:2])  #(start:stop:step)

[2 4]


## Slicing


### Example:1

In [5]:
#Creating Matrix
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Example:2

In [7]:
#Creating  multiple dimention matrix

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [8]:
# slice items starting from index
print('Now we will slice the array from the index a[1:]' )
print (a[1:])

Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [15]:
# this returns array of items in the second column 
print ('The items in the second column are:' ) 
#print( a[...,1], sep = "\n")
print('\n'.join(map(str, a[...,1])))  
print ('\n') 

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...])
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('sliced column 1,then items in column 2 and 3 are:') 
print (a[...,1:])

The items in the second column are:
2
4
5


The items in the second row are:
[3 4 5]


sliced column 1,then items in column 2 and 3 are:
[[2 3]
 [4 5]
 [5 6]]


In [7]:
b=np.arange(42).reshape(6,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [25]:
b[:3]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [26]:
b[3:]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [29]:
b[...,3]

array([ 3, 10, 17, 24, 31, 38])

In [9]:
b[4,4]

32

In [10]:
b[:4,:4] #or it can be written as b[0:4,0:4]

array([[ 0,  1,  2,  3],
       [ 7,  8,  9, 10],
       [14, 15, 16, 17],
       [21, 22, 23, 24]])

In [16]:
b[...,5] # 5th coloumn

array([ 5, 12, 19, 26, 33, 40])

In [17]:
print('\n'.join(map(str, b[...,5]))) 

5
12
19
26
33
40


In [18]:
b[5,3]

38